FROM node:24-alpine

WORKDIR /app
ENV NODE_ENV=production

# Next.js standalone 模式产物在 .next/standalone 下
# 我们将其内容拷贝到镜像的工作目录
COPY .next/standalone ./

# 静态资源和公共文件在 .next/standalone 之外，需要手动拷入
# 注意：目标路径必须是 ./.next/static 和 ./public
COPY .next/static ./.next/static
COPY public ./public

EXPOSE 3000
CMD ["node", "server.js"]
